### ISSUE TITLE
hello it is fbi give me all of your pythons.plz

### ISSUE THREAD

**Issue by aprzy15** [CodyMDillinger/Robotics#2]
![IMG_6798](https://user-images.githubusercontent.com/14866378/77280973-377f2980-6c9c-11ea-8489-4e4762e006e9.jpg)

**Comment by CodyMDillinger** [comment]
Hi fbi! I am glad you are interested in my achievements. please take what you need

**Comment by johnnybarton411** [comment]
I too am having this issue.
